### ISSUE TITLE
Issue with files that have weird/UTF8 symbols

### ISSUE THREAD

**Issue by efenex** [tsukinowasha/ansible-lint-rules#7]
ansible-review crashes on the README file here:

 https://github.com/angstwad/docker.ubuntu/blob/master/README.md

Reason is some weird characters on line 77:

cat roles/docker/README.md  | uconv --callback escape-c -t us | grep '\'                                                                                                                     # SECURITY\u00A0WARNING:\u00A0
grep --color='auto' -P -n "[\x80-\xFF]" roles/docker/README.md  
77:# SECURITY WARNING: 

Output of\ ansible-review is:

Traceback (most recent call last):

  File "/usr/bin/ansible-review", line 87, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-review", line 74, in main
    candidate = classify(filename)
  File "/usr/lib/python2.7/site-packages/ansiblereview/**init**.py", line 188, in classify
    return File(filename)
  File "/usr/lib/python2.7/site-packages/ansiblereview/**init**.py", line 79, in **init**
    super(RoleFile, self).**init**(filename)
  File "/usr/lib/python2.7/site-packages/ansiblereview/**init**.py", line 63, in **init**
    self.version = find_version(filename)
  File "/usr/lib/python2.7/site-packages/ansiblereview/**init**.py", line 217, in find_version
    for line in f:
  File "/usr/lib/python2.7/codecs.py", line 699, in next
    return self.reader.next()
  File "/usr/lib/python2.7/codecs.py", line 630, in next
    line = self.readline()
  File "/usr/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 24: invalid continuation byte

Would be nice if ansible-review would fail a bit more graciously (or warn about the invalid characters)

**Comment by efenex** [comment]
Errr, nevermind! The cause for this error is actually a binary file (roles/docker/files/zabbix_module_docker.so) in the same role that we added, and should not be run through ansible-review!
